name: "Terraform Identity GitOps"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Automated Apply"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: "Setup HashiCorp Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Apply"
        run: terraform plan 
